name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend # ✅ This should point to your Dockerfile directory
        file: ./backend/Dockerfile  # ✅ Explicit Dockerfile path
        tags: my-backend:latest
        outputs: type=docker

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "./Login-Backend/*"
        target: "~/app"

    - name: Run Docker container on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/app
          docker build -t my-backend .
          docker stop backend || true
          docker rm backend || true
          docker run -d --name backend -p 3000:3000 my-backend
